DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;
SET COLLATION ENGLISH STRENGTH PRIMARY;

CREATE TABLE users
(
  id BIGINT IDENTITY PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL,
  role VARCHAR NOT NULL DEFAULT 'ROLE_USER'
);

CREATE TABLE books
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR NOT NULL,
  isbn VARCHAR NOT NULL,
  author VARCHAR NOT NULL,
  user_id BIGINT,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
